task-JDP201101-13
piotr-grosicki/project-jdp-2011-01 pull request #12
Opened 2020-11-23 12:41 UTC by PaulinaSlowik

Created Group entity.
I have to apply changes after adding the Product class and Lombok in build.gradle that's why I set up a label WIP.

2020-11-27 14:12 UTC, PaulinaSlowik commented
task-JDP201101-13, Group Entity, GroupRepository- implementation

2020-11-27 18:27 UTC, piotr-grosicki requested changes

2020-11-27 18:27 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Group.java
> +    @NotNull
not null jest zbedne na kolumnach (`Column` posiada pole `nullable`)

2020-11-27 18:27 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<Group> findAll();
przy `CrudRepository` nie musimy robic `override` metod

2020-11-27 23:17 UTC, PaulinaSlowik commented
Changes as requested. Entities moved to domain package. Added- Entity- to entity names.Complement ProductEntity

2020-11-30 06:52 UTC, LukaszLizewski commented
Wydaje mi się, że jest jeszcze tutaj konflikt do rozwiązania.

2020-11-30 08:15 UTC, PaulinaSlowik commented
Merge main branch and resolve conflicts.

2020-11-30 20:10 UTC, ArdianM90 requested changes
Jedna uwaga, którą wydaje mi się, że trzeba poprawić - reszta to kosmetyka.

Np. można pomyśleć nad jednolitym nazewnictwem zmiennych w encjach. Tutaj mamy id, groupName i products. Dodajemy przedrostek z nazwą encji, czy nie (groupName, czy po prostu name) - moim zdaniem nie potrzeba. W przyszłości korzystając z getterów prościej będzie napisać jakasGrupa.getName niż jakasGrupa.getGroupName(). Nazwa gettera była by też identyczna z nazwą pobieranej zmiennej.

2020-12-01 08:46 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/GroupEntity.java
> +    public GroupEntity() {
zrobione

2020-12-01 08:46 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +public interface GroupRepository extends CrudRepository<GroupEntity, Integer> {
zmieniłam na Long

2020-12-01 08:47 UTC, PaulinaSlowik commented
> Jedna uwaga, którą wydaje mi się, że trzeba poprawić - reszta to kosmetyka.
> 
> Np. można pomyśleć nad jednolitym nazewnictwem zmiennych w encjach. Tutaj mamy id, groupName i products. Dodajemy przedrostek z nazwą encji, czy nie (groupName, czy po prostu name) - moim zdaniem nie potrzeba. W przyszłości korzystając z getterów prościej będzie napisać jakasGrupa.getName niż jakasGrupa.getGroupName(). Nazwa gettera była by też identyczna z nazwą pobieranej zmiennej.

zmieniłam nazwę z groupName na name

2020-12-01 17:55 UTC, ArdianM90 approved these changes
Ok

2020-12-01 19:28 UTC, piotr-grosicki approved these changes

2020-12-01 19:28 UTC, merged