task-JDP201101-11
piotr-grosicki/project-jdp-2011-01 pull request #15
Opened 2020-11-24 20:32 UTC by aleksander-lockhart

2020-11-24 21:17 UTC, aleksander-lockhart commented
Niestety nie wiem dlaczego 'task' z testow przestal sie wykonywać... bardzo prosiłbym o podpowiedź bądź nakierowanie na rozwiązanie.

2020-11-24 23:24 UTC, piotr-grosicki requested changes

2020-11-24 23:24 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private int order_id;
pola w javie nazywamy w camelcase (czyli np `orderId`) - do poprawy wszystkie pola w tym pull requescie, ktore uzywaja `_`

2020-11-25 06:09 UTC, aleksander-lockhart commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    private int order_id;
Niestety to nie to. Dzisiaj na spokojnie będę budował encję od początku - kawałek po kawałku. Zapewne trafię na miejsce z błędem :)

2020-11-25 06:21 UTC, closed without merging