Order Entity - implementation (revised from the start)
piotr-grosicki/project-jdp-2011-01 pull request #17
Opened 2020-11-25 19:56 UTC by aleksander-lockhart

Przepisane od początku (pisanie po 14h roboty kodu ma swoje wielkie_wady_i_bledy).

Posprzatany takze git (bylo chyba z 13 commitow - trzeba bylo wymiesc, branch zresetowany)

2020-11-26 07:39 UTC, piotr-grosicki requested changes

2020-11-26 07:39 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderEntity.java
> +    @NotNull
w hibernate not null zakladamy na adnotacji column (https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/Column.html#nullable())

2020-11-26 08:57 UTC, aleksander-lockhart commented on src/main/java/com/kodilla/ecommercee/domain/OrderEntity.java
> +    @NotNull
hm, @NotNull zostało wzięte z kursu kodilli - jako adnotacja @, w rozdziale o tworzeniu encji. Chyba, że coś mylę - ale tam adnotacji przy Column nie było. Stąd inny zapis.
Zmienione pod wskazanie.

2020-11-27 08:05 UTC, piotr-grosicki approved these changes

2020-11-27 08:05 UTC, merged