Task jdp201101 15
piotr-grosicki/project-jdp-2011-01 pull request #18
Opened 2020-11-27 16:48 UTC by DagmaraSkorupska

2020-11-27 17:18 UTC, piotr-grosicki requested changes
projekt sie nie buduje, `Cart` chyba powinien miec `User`

2020-11-30 12:33 UTC, PaulinaSlowik approved these changes

2020-11-30 16:06 UTC, ArdianM90 requested changes

2020-12-01 08:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public void setCartEntity(CartEntity cartEntity) {
tak raczej nie moze byc, hibernate musi wiedziec jak przypisac cart entity dla danego usera

2020-12-01 09:45 UTC, piotr-grosicki requested changes
do poprawy komentarze @ArdianM90

2020-12-01 18:04 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public void setCartEntity(CartEntity cartEntity) {
Po rozmowie z @LukaszLizewski (https://github.com/piotr-grosicki/project-jdp-2011-01/pull/20#discussion_r532194952) - uważam, że getter i setter powinny zostać, a metody addToCart() i removeFromCart() będą dodane dopiero w kolejnym tasku,. Na to jest za wcześnie, ale uważam, że sama zmienna cartEntity powinna być inicjalizowana - jak uważasz?

2020-12-01 19:03 UTC, DagmaraSkorupska reviewed
Powinno być już ok ;)

2020-12-01 19:25 UTC, ArdianM90 approved these changes
Ok

2020-12-01 19:29 UTC, piotr-grosicki approved these changes

2020-12-01 19:29 UTC, merged