Jdp201101 3
piotr-grosicki/project-jdp-2011-01 pull request #19
Opened 2020-11-28 11:12 UTC by LukaszLizewski

2020-11-28 11:27 UTC, LukaszLizewski commented
tutaj pozwolę sobie dodać że musiałem dodatkowo skomitować i spullować branch nr 3 oraz 33 ze względu na dodane zależności (lombok i conector MySQL), po dodaniu zależności projekt buduje się prawidłowo.

2020-11-28 17:23 UTC, DagmaraSkorupska commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
>      private long userId;
W tej klasie chyba nie jest potrzebne userId? Tylko w encji

2020-11-28 18:24 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
>      private long userId;
Wydaję mi się, że w późniejszych zadaniach będzie potrzebne te pole dla mappera.

2020-11-29 22:05 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
>      private long userId;
Jak dla mnie wszystko się zgadza, zmiany dodane.
W Postmanie wszystko się ładnie wyświetla.

2020-11-30 08:28 UTC, PaulinaSlowik approved these changes

2020-11-30 08:28 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/CartController.java
> +    public List<String> getProductsCart (@RequestParam long cartId, @RequestParam long productId) {
Nazwa metody jest nadal inna niż value ale według mnie nie ma to znaczenia, bo tak jak wcześniej rozmawialiśmy to nie wprowadza już w błąd. Ja bym to zostawiła tak jak jest.

2020-11-30 09:15 UTC, piotr-grosicki approved these changes

2020-11-30 09:15 UTC, piotr-grosicki requested changes
konflikty

2020-12-02 18:09 UTC, adamrozycki00 approved these changes

2020-12-02 18:11 UTC, piotr-grosicki approved these changes

2020-12-02 18:11 UTC, merged