Create ProductDto, update ProductController
piotr-grosicki/project-jdp-2011-01 pull request #2
Opened 2020-11-19 11:50 UTC by DagmaraSkorupska

2020-11-19 20:31 UTC, piotr-grosicki requested changes

2020-11-19 20:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto getProduct(){
w tej metodzie powinien byc przekazany id produktu ktory chcemy pobrac

2020-11-19 20:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +        }
formatowanie

2020-11-20 09:29 UTC, DagmaraSkorupska commented on src/main/java/com/kodilla/ecommercee/ProductController.java
> +    public ProductDto getProduct(){
Zmiany poprawione w nowym commicie

2020-11-20 18:41 UTC, piotr-grosicki approved these changes

2020-11-20 18:41 UTC, merged