Jdp201101 14
piotr-grosicki/project-jdp-2011-01 pull request #20
Opened 2020-11-28 17:57 UTC by LukaszLizewski

It need to be reviewed. ;)

2020-11-30 15:43 UTC, PaulinaSlowik requested changes
Jeszcze dwie ogólne sprawy:
1. Dlaczego w nazwach używasz Stub? Wydaje mi się że lepiej jak użyjesz git pulla na głównym branchu bo tam już jest większość utworzonych klas i możesz z nich skorzystać, ewentualnie dopiszesz metody które są Tobie potrzebne.
2.  Użyj na koniec Ctr + Alt + L dla sformatowania lini kodu w klasach tak dla lepszej czytelności ;)

2020-11-30 15:43 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      public GroupDto updateGroup(@RequestBody GroupDto groupDto) {
potrzebne dopiero w tasku JDP201101-23

2020-11-30 17:43 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +public class CartDto {
Tak wg mnie również.

2020-11-30 17:47 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +
Adnotacja @NotNull jest przy getterze. Myślisz, że przy setterze też jest wymagana?

2020-11-30 17:48 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/service/DbCartService.java
> +public class DbCartService {
Tak, potwierdzam

2020-11-30 17:51 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +    public List<StubProduct> getStubProduct() {
Tak mogę zmienić na tę chwile jednakże przy kolejnym tasku - rzeczywista implementacja encji Cart kolejny raz zmienię nazwę metod już a docelowe

2020-11-30 17:52 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +    public void setStubProduct(List<StubProduct> stubProduct) {
Aby było jaśniej oczywiście należy to zmienić i zmienię :)

2020-11-30 17:52 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
>      public GroupDto updateGroup(@RequestBody GroupDto groupDto) {
Tak, potwierdzam

2020-11-30 17:55 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +    public void setStubProduct(List<StubProduct> stubProduct) {
Wydaje mi się, że dla metod addProduct i removeProduct ich rzeczywista implementacja będzie przy kolejnym tasku, nie sądzisz? Metody te będą miały nazwy identyczne lub zbliżone jak w CartController. ;)

2020-11-30 18:07 UTC, LukaszLizewski commented
1) Dlaczego w nazwach używasz Stub? Wydaje mi się że lepiej jak użyjesz git pulla na głównym branchu bo tam już jest większość utworzonych klas i możesz z nich skorzystać, ewentualnie dopiszesz metody które są Tobie potrzebne.
_no właśnie jak zabierałem się za pisanie tasku 14 po pullowaniu na branchu main nie było jeszcze żadnych implementacji encji dlatego pozostawiłem w nazwie Stub aby jednoznacznie zaznaczyć encje wydmuszki, w rzeczywistej implementacji klasy Stub zostaną usunięte a relacje pomiędzy rzeczywistymi Entity powiązane _

2) Użyj na koniec Ctr + Alt + L dla sformatowania lini kodu w klasach tak dla lepszej czytelności ;)
_OK_

2020-11-30 19:47 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +    public void setStubProduct(List<StubProduct> stubProduct) {
W kolejnym tasku, czyli "... rzeczywista implementacja" - w sumie tak.

2020-12-02 19:12 UTC, adamrozycki00 requested changes
Wymagane zmiany uzgadniające kod do innych PR (Task 24 i Task 25).

2020-12-02 19:12 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/StubProduct.java
> +public class StubProduct {
Zmieniłbym na zwykłą nazwę klasy - ProductEntity

2020-12-02 19:12 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/StubUser.java
> +public class StubUser {
Zmieniłbym na zwykłą nazwę klasy - UserEntity. Poza tym mam prośbę o uzgodnienie tej klasy do wersji zapisanej w PR Task 25.

2020-12-02 19:12 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/StubProductRepository.java
> +public interface StubProductRepository extends JpaRepository<StubProduct, Long> {
Zmieniłbym na zwykłą nazwę klasy - ProductRepository.

2020-12-02 19:12 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/StubUserRepository.java
> +public interface StubUserRepository extends JpaRepository<StubUser, Long> {
Zmieniłbym na zwykłą nazwę klasy - UserRepository. Poza tym mam prośbę o uzgodnienie tej klasy do wersji zapisanej w PR Task 25.

2020-12-02 19:12 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/service/DbCartService.java
> +    public CartEntity createCart (final CartEntity cart) {
Nazwałbym tę metodę `saveCart`.

2020-12-02 22:13 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/StubProduct.java
> +public class StubProduct {
OK

2020-12-02 22:13 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/StubUser.java
> +public class StubUser {
OK

2020-12-02 22:13 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/repository/StubProductRepository.java
> +public interface StubProductRepository extends JpaRepository<StubProduct, Long> {
OK

2020-12-02 22:13 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/repository/StubUserRepository.java
> +public interface StubUserRepository extends JpaRepository<StubUser, Long> {
OK

2020-12-02 22:17 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/service/DbCartService.java
> +    public CartEntity createCart (final CartEntity cart) {
Może być

2020-12-02 22:18 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +@Component
Masz rację,  `@component` został mi po walce z budowaniem projektu po merge-owaniu maina :)

2020-12-02 22:21 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    private CartEntity cart;
Dzieje z pierwszej implementacji. Mogę skasować ale wydaję mi się, że będzie potrzebny do rzeczywistej implementacji metod.

2020-12-02 22:24 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @RequestMapping(method = RequestMethod.POST, value = "createOrder")
Czy to nie jest cześć zadania do rzeczywistej implementacji metod kontrolera??

2020-12-02 22:35 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @RequestMapping(method = RequestMethod.POST, value = "createOrder")
Dostosowano, rozumiem że chodzi ci o pola które jeszcze nie są w gałęzi main?

2020-12-02 22:40 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
>  package com.kodilla.ecommercee.controller;
Muszę w takim razie przekopiować klasę `UserController ` + klasy, które na nowo wykonałeś w tym PR. Jeśli powiesz mi jak to sprawnie zrobić aby ręcznie kodu nie kopiować, nie ma sprawy.

2020-12-03 14:33 UTC, adamrozycki00 approved these changes

2020-12-03 14:33 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
>      @RequestMapping(method = RequestMethod.POST, value = "createOrder")
Nie, to jednak bez sensu, bo jeśli twój PR będzie merdżowany przed moim, to nie zbuduje projektu. Sorki, to sprawdź, czy Ci się buduje w tej postaci, a jak nie, to przywróć poprzednie zmiany (chodzi tylko o te miejsca, w których wskazywałem, że powinny być uzgodnione z pozostałymi PR, Task 24 i Task 25). Dam Ci approve i sam uzgodnię wszystko w swoich PR.

2020-12-03 14:33 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +public class OrderEntityTestSuite {
A to nie jest już inny task? #16?

2020-12-03 14:48 UTC, piotr-grosicki requested changes

2020-12-03 14:48 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +/*
czemu ta klasa jest zakomentowana?

2020-12-03 15:19 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +public class OrderEntityTestSuite {
Tak niestety wkradł mi się task 16

2020-12-03 15:21 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +/*
Ta klasa jest zakomentowana ponieważ jest częścią tasku 16 który właśnie  robię i najwyraźniej omylnie została dodana do commita. Wykasuję ją dla zachowania porządku.

2020-12-03 16:05 UTC, PaulinaSlowik approved these changes

2020-12-03 20:28 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +/*
tak, powinna zostac usunieta :) nie trzymamy zakomentowanego kodu w repozytorium

2020-12-04 09:14 UTC, DagmaraSkorupska approved these changes

2020-12-04 16:57 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +public class OrderEntityTestSuite {
Wykasowano

2020-12-04 16:57 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +/*
Wykasowałem

2020-12-04 17:26 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    //private CartEntity cartEntity = new CartEntity();
Wyczyszczono kod z komentarzy.

2020-12-05 11:35 UTC, piotr-grosicki approved these changes

2020-12-05 11:35 UTC, merged