Task 25
piotr-grosicki/project-jdp-2011-01 pull request #22
Opened 2020-11-28 20:41 UTC by adamrozycki00

2020-12-02 13:34 UTC, adamrozycki00 commented
Adjusted the UserDto class to the current of UserEntity class. Added field isBlocked into both classes.

2020-12-04 18:24 UTC, DagmaraSkorupska approved these changes

2020-12-05 11:35 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2020-12-06 11:16 UTC, DagmaraSkorupska approved these changes

2020-12-06 11:19 UTC, piotr-grosicki approved these changes

2020-12-06 11:19 UTC, merged