Task 24
piotr-grosicki/project-jdp-2011-01 pull request #23
Opened 2020-12-02 17:08 UTC by adamrozycki00

2020-12-04 17:05 UTC, piotr-grosicki requested changes
konflikty do rozwiazania

2020-12-04 18:18 UTC, DagmaraSkorupska reviewed
konflikty

2020-12-04 20:00 UTC, adamrozycki00 commented
Konflikt rozwiązany.

2020-12-05 11:35 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2020-12-05 11:43 UTC, DagmaraSkorupska reviewed
konflikty

2020-12-05 11:44 UTC, DagmaraSkorupska requested changes
konflikty

2020-12-06 11:16 UTC, DagmaraSkorupska approved these changes

2020-12-06 11:18 UTC, piotr-grosicki requested changes

2020-12-06 11:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private List<ProductEntity> products;
`OrderDto` nie moze zawierac `ProductEntity` tylko `ProductDto` lub same ich id

2020-12-06 11:18 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private UserEntity userEntity;
to samo tutaj

2020-12-06 12:15 UTC, piotr-grosicki requested changes
+ konflikty

2020-12-06 12:59 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private List<ProductEntity> products;
OK. Czekam w takim razie na rzeczywistą implementację ProductControllera.

2020-12-06 18:53 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private List<ProductEntity> products;
@piotr-grosicki ta uwaga dotyczy wszystkich dto, tak?

2020-12-06 19:43 UTC, LukaszLizewski approved these changes

2020-12-06 22:51 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private OrderService service;
Czy tutaj nie powinna być adnotacja @Autowired?

2020-12-07 00:00 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    private OrderService service;
Powinna, bo się zmienna nie zainicjuje.

2020-12-08 19:54 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
>      private List<ProductEntity> products;
Rzeczywista implementacja ProductControllera czeka na review - task 21.

2020-12-11 20:08 UTC, adamrozycki00 commented
Czekam na merge PR-u #26

2020-12-12 21:14 UTC, aleksander-lockhart approved these changes

2020-12-14 16:31 UTC, merged