Task 20
piotr-grosicki/project-jdp-2011-01 pull request #24
Opened 2020-12-06 17:59 UTC by adamrozycki00

2020-12-06 20:27 UTC, ArdianM90 requested changes

2020-12-06 20:27 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
Jak dla mnie w orElse() powinien być wyrzucony błąd NoSuchUserException(). W tej chwili sprawdzane jest czy user1 jest zablokowany, a jeżeli funkcja wogóle nie znajdzie takiego usera (który powinien być) - sprawdza drugiego - co jeśli drugiego też nie znajdzie.

2020-12-06 20:27 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        assertEquals(true, returnedUser.getIsBlocked());
Linie 89 i 90 nie współgrają z sekcją Given&When. Ja bym widział ten test tak, że przypisujemy nie zablokowanego użytkownika do zmiennej1, potem go blokujemy i przypisujemy do zmiennej 2. W asercji sprawdzamy stany isBlocked obu zmiennych, bo chcemy sprawdzić czy .blockUser() rzeczywiście działa.

Powinna też być klasa NoSuchUserException(), bo .blockUser jest typu Optional<UserEntity>, więc może nie znaleźć użytkowika o podanym Id.

2020-12-06 20:27 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        repository.deleteById(user1.getUserId());
Temat do dyskusji, ale wydaje mi się, że nie bez powodu w testach stosuje się schemat - given -> when -> then. Najpierw tworzymy stan wejściowy bazy z konkretnym użytkownikiem -> potem go usuwamy -> potem sprawdzamy czy został usunięty. Jeśli ktoś w przyszłości zmieni testy, tak że inny będzie usuwał user1 z bazy, to ten test się wykona mimo tego, że nic nie usunie.

2020-12-06 20:27 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        assertEquals(1, Iterables.size(repository.findAll()));
Ja bym sprawdzał czy konkretny (usunięty) użytkownik jest w bazie. Ilość użytkowników może się zmianiać jak ktoś w przyszłości zmodyfikuje testy.

2020-12-06 20:35 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(String userName, String userPassword, String userEmail) {
Usunąłem, bo i tak nic nie dawał. Id jest nadawane automatycznie. Mapper tak samo - jeśli tworzy nowego usera, to z nadanym automatycznie id.

2020-12-06 20:50 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(String userName, String userPassword, String userEmail) {
W sumie racja - w edycji usera też się nie przyda, bo id nie powinno być edytowane.

2020-12-06 20:55 UTC, ArdianM90 requested changes

2020-12-06 20:55 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +    @Before
Wiem, że tworzysz tutaj stan wejściowy bazy danych, który przy twoich testach się sprawdzi. Uważam jednak, że stan wejściowy powinien być tworzony w każdym teście w sekcji Given, bo same testy mogą się zmieniać razem z głównym kodem programu - z każdą zmianą trzeba będzie od początku analizować czy stan wejściowy nie jest modyfikowany przez kolejne testy, i czy to nie wpływa na działanie następnych.

2020-12-06 20:57 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
Pierwsza asercja i tak sprawdza, czy user2 ma flagę isBlocked ustawioną na false. Więc jest pewność, że jeśli test przeszedł, to user1 został poprawnie pobrany z bazy. Poza tym user2 nie jest pobierany z bazy, tylko tworzony w kodzie (nie jest istotne, czy ani jak user2 się zapisuje w bazie lub z niej pobiera).

Wyrzucony wyjątek od razu by mówił, jaka jest przyczyna uwalonego testu, to prawda. Ja jednak wolę, jak mi test nie przechodzi i elegancko pokazuje różnicę między expected i resulted, niż gdy się wywala z komunikatem o wyjątku.

2020-12-06 21:03 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +    @Before
No ale przed każdym testem puszczana jest metoda setUp i po każdym puszczana cleanUp. Czyli stan wejściowy faktycznie jest tworzony przed każdym testem.

2020-12-06 21:10 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
Z tego co wiem, zasada jest taka, że jeden test sprawdza jedną funkcję. Pytanie co ten test ma sprawdzać:
a) czy .blockUser zapisuje blokadę użytkownika w bazie?
b) czy może, czy .blockUser ustawia wartość isBlocked w obiekcie User na true.

2020-12-06 21:14 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        assertEquals(true, returnedUser.getIsBlocked());
Nie współgrają? :) Nie rozumiem tej uwagi.

2020-12-06 21:15 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        repository.deleteById(user1.getUserId());
OK. zmienię to.

2020-12-06 21:21 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
Są dwa odrębne testy metody blockUser: jeden sprawdza, czy obiekt zwracany z tej metody (returnedUser) jest zablokowany, a drugi sprawdza, czy obiekt pobrany z bazy po zastosowaniu na nim tej metody (retrievedUser) jest zablokowany.

2020-12-06 21:31 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        assertEquals(true, returnedUser.getIsBlocked());
Nie ogarnąłem idei z robieniem dwóch testów: encji pobranej z bazy i obiektu user2.

2020-12-06 21:31 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +    @Before
Ok

2020-12-06 21:52 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
No, dobra. W takim razie jeżeli user1 nie zostanie zablokowany w linii 87, to to test sprawdzi dwa razy user2. Jedna asercja się wykona, a druga nie. Gdybym sam czytał test, nie zrozumiał bym co on testuje.

Uważam, że można to zrobić w prostszy i czytelniejszy sposób: pobranie użytkownika, zablokowanie i porównanie stanu przed blokadą z tym po blokadzie, ale to tylko opinia :)

2020-12-06 21:53 UTC, ArdianM90 approved these changes

2020-12-06 22:13 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
Czy w testach nie powinniśmy również sprawdzić działania relacji między encjami? Z tego co pamiętam Piotr mówił, że mamy takie testy przeprowadzić.

2020-12-06 22:49 UTC, LukaszLizewski requested changes
Encja User posiada relację (np. z encją Order), brak wg mnie testów relacji z innymi encjami.

2020-12-06 23:01 UTC, PaulinaSlowik commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +public class UserEntityTestSuite {
Czy nie powinna tutaj być adnotacja @Transactional?

2020-12-06 23:01 UTC, PaulinaSlowik commented
> Encja User posiada relację (np. z encją Order), brak wg mnie testów relacji z innymi encjami.

2020-12-07 00:29 UTC, adamrozycki00 commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +public class UserEntityTestSuite {
Chyba nie musi być.

2020-12-07 00:55 UTC, adamrozycki00 commented
> > Encja User posiada relację (np. z encją Order), brak wg mnie testów relacji z innymi encjami.
> 
> Dokładnie też się nad tym zastanawiałam czy nie powinno się testować Order, Cart..?

Wydaje mi się, że testy relacji powinny być w obu wypadkach po drugiej stronie relacji. Trzeba wybrać, gdzie taki test będzie, bo inaczej się zakleszczymy: nie przejdzie PR z testami usera, bo nie testuje relacji z orderami, ale żeby go zrobić, musimy mieć klasy orderu przetestowane, czego nie zrobimy, bo musielibyśmy przetestować relację z userem, a jego testy właśnie wiszą... User może sobie istnieć bez orderów, a ordery bez usera nie, więc tę relację testowałbym po stronie orderów. Podobnie z cartem: user nic nie wie o swoim carcie, a cart musi mieć usera, więc i w tym wypadku testowałbym po drugiej stronie.

2020-12-07 08:53 UTC, piotr-grosicki requested changes

2020-12-07 08:53 UTC, piotr-grosicki commented on build.gradle
> +    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
czemu to zostalo dodane bez konsultacji z grupa?

2020-12-07 08:53 UTC, piotr-grosicki commented on build.gradle
> +    compile group: 'com.google.guava', name: 'guava', version: '29.0-jre'
czemu to zostalo dodane bez konsultacji z grupa?

2020-12-07 08:53 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +        return EqualsBuilder.reflectionEquals(this, that, "orders");
zbedne importowanie calej biblioteki zeby uzyc jej do `equals` i `hashCode`. Szczegolnie ze w javie 8+ mamy juz gotowe klasy do skrocania np `hashCode` (`Objects`)

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        assertEquals(2, Iterables.size(repository.findAll()));
podczas testu zapisu encje powinny byc zapisywane w sekcji given, nie w `before` dla klasy testowej

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity retrievedUser1 = service.getUser(user1.getUserId()).orElse(null);
testy nie powinny zawierac kodu `orElse` tylko powinny przeprowadzac assercje na zwroconych optionalach

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity retrievedUser = service.getUser(user1.getUserId()).orElse(user2);
zwracanie `user2` w przypadku niepowodzenia pobrania `user1` jest nieintuicyjne i wprowadza niepotrzebne zamieszanie. assercje powinny byc przeprowadzane na optionalach

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity returnedUser = service.blockUser(user1.getUserId()).orElse(user2);
tak samo jak koledzy wyzej napisali, test jest teraz nielogiczny i nieintuicyjny. Testujemy jedna rzecz (pobieranie zablokowanego uzytkownika) a nie to czy pobranie uzytkownika jest w ogole mozliwe wiec wyjatek jest tutaj jak najbardziej na miejscu (czyli po prostu bez uzycia `orElse` - dzialamy na optionalu)

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        long countSavedUsersBeforeDeletion = Iterables.size(repository.findAll());
niepotrzebne uzycie `Iterables` skoro zwracana jest lista i mozna po prostu uzyc metody `size()`. tym samym guava do wywalenia

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        UserEntity deletedUser = service.getUser(deletedUserId).orElse(null);
tutaj nie powinien byc uzyty `orElse` tylko assercje na optionalach

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +    public void shouldDeleteUser() {
brakuje testow ktore sprawdzaja czy usuniecie uzytkownika nie usuwa encji, z ktorymi uzytkownik mial relacje (lub usuwa, zalezy od kontekstu)

2020-12-07 08:53 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +            service.saveUser(user1);
duzo czytelniej i latwiej zrozumiec jest testy gdzie potrzebne encje zapisywane sa w poszczegolnych testach a nie globalnie dla calej klasy. poprzez zastosowanie metody `Before` zapisujacej dany poniekad ukrywamy logike, ktora powinna byc widoczna patrzac na pojedyncza metode testowa

2020-12-07 09:18 UTC, adamrozycki00 commented on build.gradle
> +    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
A czemu nie? Przecież nie ustaliliśmy, że dodawanie bibliotek będziemy konsultować przed PR. A PR to też możliwość konsultacji.

2020-12-07 09:18 UTC, adamrozycki00 commented on build.gradle
> +    compile group: 'com.google.guava', name: 'guava', version: '29.0-jre'
Uznałem, że to nasz standard, bo jest w materiałach kursowych.

2020-12-07 09:22 UTC, DagmaraSkorupska commented on build.gradle
> +    compile group: 'com.google.guava', name: 'guava', version: '29.0-jre'
W którym module?

2020-12-07 10:29 UTC, piotr-grosicki commented on build.gradle
> +    compile group: 'com.google.guava', name: 'guava', version: '29.0-jre'
dorzucanie guavy tylko zeby uzyc `Iterables` wg mnie nie ma sensu, szczegolnie ze repository zwraca liste wiec mozna wywolac po prostu `size()`

2020-12-07 10:30 UTC, piotr-grosicki commented on build.gradle
> +    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.11'
z drugiej strony: na pewno jest sens dodawac biblioteke, ktora robi dokladnie to samo co java? :)

2020-12-07 10:35 UTC, piotr-grosicki commented
> > > Encja User posiada relację (np. z encją Order), brak wg mnie testów relacji z innymi encjami.
> > 
> > 
> > Dokładnie też się nad tym zastanawiałam czy nie powinno się testować Order, Cart..?
> 
> Wydaje mi się, że testy relacji powinny być w obu wypadkach po drugiej stronie relacji. Trzeba wybrać, gdzie taki test będzie, bo inaczej się zakleszczymy: nie przejdzie PR z testami usera, bo nie testuje relacji z orderami, ale żeby go zrobić, musimy mieć klasy orderu przetestowane, czego nie zrobimy, bo musielibyśmy przetestować relację z userem, a jego testy właśnie wiszą... User może sobie istnieć bez orderów, a ordery bez usera nie, więc tę relację testowałbym po stronie orderów. Podobnie z cartem: user nic nie wie o swoim carcie, a cart musi mieć usera, więc i w tym wypadku testowałbym po drugiej stronie.

jezeli user posiada relacje do orders, nalezy sprawdzic co sie stanie z orderami po usunieciu usera w testach usera

2020-12-08 21:28 UTC, LukaszLizewski requested changes
Właśnie ukończyłem test `Order` i tak jak napisałeś sprawdziłem co się stanie kiedy usunę order (czy przypadkiem nie usunę user) ale również wykonałem test w drugą stronę czyli sprawdziłem czy order usunie się kiedy usunę user. Dzięki tym testom zauważyłem kilka małych błędów w `OrderEntity`, `ProductEntity` oraz `UserEntity` i nadal uważam, że powinny zostac wykonane testy relacji. Zapraszam do review JDP201101-16

2020-12-11 11:39 UTC, adamrozycki00 commented
Test zapisu użytkownika zawiera teraz zapis użytkownika w sekcji "when".
Asercje są na optionalach (tam gdzie optionale występowały w sekcji "when").
Usunąłem testy metody usuwającej użytkownika, bo to metoda repozytorium; serwis nie ma takiej metody.
Dodałem testy relacji z koszykiem (zmieniłem przy tym definicję relacji w CartEntity).

2020-12-11 19:38 UTC, adamrozycki00 commented on src/test/resources/logback-test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Ten pliczek xml służy ograniczeniu logowania przy uruchomieniu testów, tak żeby nie leciały logi poziomu DEBUG, których jest bardzo dużo.

2020-12-11 19:41 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +    @OneToOne(mappedBy = "cart")
Zmiana definicji relacji UserEntity-CartEntity. Tabela CARTS nie ma teraz pola z id usera.

2020-12-12 21:10 UTC, ArdianM90 approved these changes
Nie wiem czy konieczne jest tworzenie jednoelementowej mapy obiektów typu UserEntity w teście shouldRetrieveSavedUsers(), ale nie wiem też jak to inaczej rozwiązać. 
Próbowałem: assertTrue(retrievedUser1.isPresent()), ale Intelij podkreśla, że jest zawsze true, więc chyba nie.

Ode mnie approve.

2020-12-14 08:18 UTC, merged