pierwszy zarys testów, prosze o pomoc
piotr-grosicki/project-jdp-2011-01 pull request #25
Opened 2020-12-07 12:00 UTC by DagmaraSkorupska

2020-12-07 23:13 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
UserEntity w mainie nie posiada pola cart, więc trzeba będzie to dodać. Według mnie cart powinien być przypisywany użytkownikowi w konstruktorze, bo raczej nie ma takiego konta w sklepie internetowym, które nie posiada koszyka. 

Przykład: new UserEntity(1L, "user", "password", "user@test.com", new CartEntity());
W tym przypadku w teście będzie tworzony użytkownik.

Przykład 2: Nowy użytkownik będzie otrzymywał w konstruktorze tylko id koszyka, więc najpierw musimy stworzyć koszyk.

Tak czy inaczej potrzebny będzie refactoring encji user.

2020-12-08 21:13 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
nie polecam robić takiego przykładu => `new UserEntity(1L, "user", "password", "user@test.com");`, pole `userId` jest generowane automatycznie dzięki `@GeneratedValue(strategy = GenerationType.IDENTITY)`, jeśli podasz jakąś wartość dla `userId` to wyłożysz testy

2020-12-08 21:14 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
problem opisałem w PR JDP201101-16

2020-12-08 22:17 UTC, ArdianM90 commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
Zmieniona encja user czeka na review i dołączenie do maina - task-34.

2020-12-09 09:28 UTC, DagmaraSkorupska commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
> nie polecam robić takiego przykładu => `new UserEntity(1L, "user", "password", "user@test.com");`, pole `userId` jest generowane automatycznie dzięki `@GeneratedValue(strategy = GenerationType.IDENTITY)`, jeśli podasz jakąś wartość dla `userId` to wyłożysz testy

tak, tak to wiem ;) bardziej chodzi mi o kolejne testy :D

2020-12-09 09:40 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
Wg mnie, na tym poziomie przy testach encji, powinnaś wykonać typowe CRUD:
- `Create` stworzyć dane do encji i sprawdzić czy się tworzą i zapisują (sprawdzasz rozmiar encji itp.)
- `Read` - sprawdzić czy się odczytują 
- `Update` - np dodajesz `product` i sprawdzasz czy się dodaje + podmieniasz `product` i sprawdzasz czy się podmienił 
-`Delete` - usuwasz zapisy w encji i sprawdzasz czy np jak usuniesz `cart` to czy przypadkiem nie usunęło `user` lub `product` 
To są podstawowe testy oczywiście możesz dołożyć inne ;)

2020-12-09 09:55 UTC, DagmaraSkorupska commented on src/test/java/com/kodilla/ecommercee/domain/CartEntityTest.java
> +        //??????cart.setUserEntity(new UserEntity(1L, "user", "password", "user@test.com"));
dzieki :)

2020-12-09 12:42 UTC, DagmaraSkorupska commented
CartEntity - należy usunąć (cascade = CascadeType.ALL), 
PYTANIE: czy usunięcie cart powoduje usunięcie produktów w ogóle, czy z konkretnego koszyka?

2020-12-12 13:58 UTC, adamrozycki00 requested changes

2020-12-12 13:58 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +   @ManyToMany(cascade = CascadeType.ALL)
Myślę, że typ `DETACH` będzie odpowiedni, bo `ALL` usunie produkty z bazy.

2020-12-13 13:25 UTC, DagmaraSkorupska commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> +   @ManyToMany(cascade = CascadeType.ALL)
w sumie racja

2020-12-13 14:10 UTC, adamrozycki00 approved these changes

2020-12-13 14:17 UTC, ArdianM90 approved these changes
W teście testSaveReadProductOfCart() porównywana jest wartość "user1" za pomocą której utworzono encję z wartością pobraną z encji za pamocą gettera (linia 82) - test sprawdza działanie konstruktora i gettera, nie bierze pod uwagę zapisu/odczytu z bazy danych. Czy testy nie powinny sprawdzać działania serwisu/repozytorium?

Zastanawia mnie czy zapis w encji jest równoznaczny z zapisem w bazie, bo sam próbuję pisać testy z użyciem repozytoriów i wywala błędy, a tutaj wszystko przechodzi.

2020-12-14 08:21 UTC, piotr-grosicki approved these changes

2020-12-14 08:22 UTC, merged