Task jdp201101 21
piotr-grosicki/project-jdp-2011-01 pull request #26
Opened 2020-12-07 22:49 UTC by ArdianM90

2020-12-11 10:48 UTC, DagmaraSkorupska approved these changes

2020-12-11 11:43 UTC, piotr-grosicki requested changes

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        editedProduct.setGroup(group);
czemu edycja produktu ustawia nowa grupe?

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        editedProduct.setCarts(carts);
czemu edycja produktu czysci carty?

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        editedProduct.setOrders(orders);
czemu edycja produktu czysci ordery?

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +        ProductEntity editedProduct = service.findById(productDto.getId()).orElseThrow(ProductNotFoundException::new);
ta logika nizej powinna znajdowac sie w serwisie, nie w controllerze

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/ProductDto.java
> +    public ProductDto(ProductEntity product) {
to powinna byc funkcjonalnosc mappera, nie konstruktora w dto

2020-12-11 11:43 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/DbService.java
> +public class DbService {
to powinno byc w serwisie odpowiedzialnym za obsluge produktu, nie w globalnym

2020-12-11 16:24 UTC, adamrozycki00 requested changes

2020-12-11 16:24 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void updateProduct (@RequestBody ProductDto productDto) throws ProductNotFoundException {
Konsternacja. W materiałach (19.3) metoda PUT jest zaimplementowana bardzo podobnie do POST, jest jednolinijkowa. Zapisuje przekazany obiekt (po przekształceniu mapperem z DTO) od razu w całości. Nie wymaga aktualizowania oddzielnie wszystkich pól. Może próbowałeś robić w taki prosty sposób i nie można było tak zrobić? (dlaczego?)

2020-12-11 16:24 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/ProductEntity.java
> +    public ProductEntity(Long id, String name, String description, double price, GroupEntity group) {
Do czego służy ten konstruktor? Nic nie robi z przekazanymi argumentami.

2020-12-11 16:24 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        ProductMapper mapper = new ProductMapper();
Zamiast nowego mappera w zagnieżdżonego w mapperze wykorzystałbym this.

2020-12-11 16:24 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    Optional<GroupEntity> findById(Long id);
Jeśli nie przedefiniowujesz tej metody, to definicja nie jest potrzebna.

2020-12-11 18:17 UTC, piotr-grosicki requested changes

2020-12-11 18:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupNotFoundException.java
> +public class GroupNotFoundException extends Exception {
nie zgodze sie, jezeli tylko mamy taka mozliwosc powinnismy rzucac swoim wlasnym customowym wyjatkiem

2020-12-11 18:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    private DbService service;
+1

2020-12-11 18:17 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
> +        ProductMapper mapper = new ProductMapper();
tak, zgadzam sie. w klasie `ProductMapper` nie powinien powstawac nowy `ProductMapper`

2020-12-11 18:20 UTC, piotr-grosicki requested changes

2020-12-11 18:20 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    public void updateProduct (@RequestBody ProductDto productDto) throws ProductNotFoundException {
+1

2020-12-12 16:12 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/controller/ProductController.java
> +    private DbService service;
Done

2020-12-12 17:24 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    Optional<GroupEntity> findById(Long id);
Done

2020-12-12 21:24 UTC, adamrozycki00 requested changes

2020-12-12 21:28 UTC, adamrozycki00 commented
Metody product mappera są takie, jakich  potrzeba, dzięki. Jest tam jedna mała rzecz do zmiany - usunięcie argumentu id przy wywołaniu konstruktora ProductEntity (skorzystanie z innego konstruktora). I w ProductEntity - zastąpienie typu double przez BigDecimal do przechowywania ceny produktu.

2020-12-12 22:02 UTC, ArdianM90 commented
@adamrozycki00 zmiany wprowadziłem tak jak pisałeś, oprócz BigDecimala - na tym etapie projektu myślę, że to jest bezcelowe. Nie będziemy nic sprzedawać w tym sklepie, a na potrzeby kursu double jest wystarczająco pojemny i odporny na niedokładność. Wolę pisać testy z task-18, niż szukać doubli do zamiany w tych, które już są :)

2020-12-12 22:46 UTC, adamrozycki00 approved these changes

2020-12-14 08:23 UTC, piotr-grosicki approved these changes

2020-12-14 08:23 UTC, merged