Refectoring encji user i cart - relacja 1-1 definiowana po stronie us…
piotr-grosicki/project-jdp-2011-01 pull request #27
Opened 2020-12-08 19:48 UTC by ArdianM90

…era.

2020-12-08 21:34 UTC, LukaszLizewski reviewed
Takie pytanko: why?
Sprawdzałem na Kanban board i nie ma opisu powodu zmian (oczywiście może mi coś umknęło...sorry), czy możesz opisać problematykę?

2020-12-08 21:41 UTC, LukaszLizewski approved these changes

2020-12-09 07:11 UTC, aleksander-lockhart approved these changes
Wygląda ok

2020-12-09 08:58 UTC, DagmaraSkorupska approved these changes

2020-12-09 09:25 UTC, LukaszLizewski reviewed
Jest lepiej ;)

2020-12-09 12:15 UTC, adamrozycki00 requested changes
Usunąłbym nadmiarowe warunki na kolumnę (w dwóch miejscach) i zmienił konsekwentnie nazwę kolumny USER_EMAIL na EMAIL.

2020-12-09 12:15 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    @Column(name = "USER_EMAIL")
Nie lepsza będzie nazwa kolumny "EMAIL"?

2020-12-09 12:15 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
Tak jest lepiej wg mnie, bo jeśli usuniemy usera, to usuniemy koszyk. Wcześniej user by ginął po usunięciu koszyka, niezbyt intuicyjnie.

2020-12-09 12:37 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/CartEntity.java
> -    private UserEntity userEntity;
Zgodnie z sugestią mentora, warto zostawić pole UserEntity (z nazwą zmienioną na "user") i dodać mapowanie @OneToOne na pole Cart w encji UserEntity. I w takim razie zmieniłbym też nazwę samego PR na samo "Refactoring relacji user-cart", bo ona byłaby definiowana po obu stronach.

2020-12-10 08:42 UTC, piotr-grosicki approved these changes

2020-12-10 08:42 UTC, merged