JDP201101-16 OrderTestSuite
piotr-grosicki/project-jdp-2011-01 pull request #28
Opened 2020-12-08 21:06 UTC by LukaszLizewski

Stworzyłem testy OrderEntity UWAGI (wg mnie) do klas:
- `OrderEntity` - należy usunąć `(cascade = CascadeType.ALL)`, usunięcie order powoduje usunięcie produktu oraz użytkownika (efekt niepożądany)
- `ProductEntity` - należy usunąć `(cascade = CascadeType.ALL)`, usunięcie product powoduje usunięcie order oraz użytkownika (efekt niepożądany)
- `UserEntity` należy zmienić `(cascade = CascadeType.ALL)` na `  cascade = CascadeType.REMOVE`, przy tym ustawieniu  kaskadowości usunięcie usera powoduje automatyczne usunięcie przypisanych do niego orderów. 
- `UserEntity` należy usunąć z konstruktora `userId`, ponieważ `userId` jest generowany automatycznie dzięki ` @GeneratedValue(strategy = GenerationType.IDENTITY)`. Proszę o komentarze.

2020-12-08 21:09 UTC, LukaszLizewski commented
Powyższe UWAGI są wprowadzone do kodu w postaci zmian lub komentarzy. Po przeprowadzeniu analizy weryfikatorów, jeżeli zgodzą się ze mną, że należy zmieniać klasy, stworzę odpowiednie taski bugi.

2020-12-08 22:16 UTC, ArdianM90 commented
W task-34 właśnie zmieniam encje usera - przy okazji usunąłem id z konstruktora. Zgadzam się z pozostałymi uwagami.

2020-12-09 12:30 UTC, DagmaraSkorupska commented
zgadzam sie sie uwagami

2020-12-09 12:38 UTC, DagmaraSkorupska approved these changes

2020-12-09 12:56 UTC, piotr-grosicki requested changes

2020-12-09 12:56 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(/*Long userId, */String userName, String userPassword, String userEmail) {
zakomentowany kod

2020-12-09 12:56 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        user1 = new UserEntity("userName1", "usersPassword1", "userEmail1");
jestem przeciwnikiem tworzenia danych testowych w metodzie `setUp`. szczegolnie jesli chodzi o testowanie zapisu, w twojej klasie tak naprawde odbywa sie w tutaj a nie w odpowiednim tescie. kazdy z testow powinien tworzyc encje, ktore testuje. tworzenie `UserEntity` i `ProductEntity` tutaj jest jak najbardziej ok, poniewaz sa to encje pomocnicze, ktore beda uzywane w testach

2020-12-09 21:06 UTC, LukaszLizewski commented on src/test/java/com/kodilla/ecommercee/OrderEntityTestSuite.java
> +        user1 = new UserEntity("userName1", "usersPassword1", "userEmail1");
Poprawiłem, usunąłem `@Before` oraz `@After`, teraz dla każdego z testów jest osobny zestaw danych `given`

2020-12-09 21:07 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(/*Long userId, */String userName, String userPassword, String userEmail) {
poprawiłem i usunąłem zakomentowany kod

2020-12-09 21:17 UTC, PaulinaSlowik approved these changes

2020-12-10 08:43 UTC, piotr-grosicki requested changes
konflikty

2020-12-10 09:03 UTC, aleksander-lockhart commented
Zmieniła się encja User - do wyprostowania konflikty przy tworzeniu danych testów.
Choć tutaj uwaga do Encji User - w konstruktorze jest także "Id" - a on jest automatycznie generowany.

2020-12-10 09:05 UTC, aleksander-lockhart commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(String userName, String userPassword, String userEmail) {
tutaj jest zmiana, która spowoduje, iż dane do testu staną się prawidłowe... ale nie wiem jak to ma się do poprawek sensu stricte. Czy powinniśmy najpierw poprawić Encje osobnym commitem - a potem dopiero robić commit testów? Było by to logiczne. Poprawiamy bazę, a potem jedynie pracujemy nad testami.

2020-12-10 16:51 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/UserEntity.java
> +    public UserEntity(String userName, String userPassword, String userEmail) {
Chciałem tak zrobić ale aby testy mi działały zakomentowałem wadliwy kod (`userID` w konstruktorze i atrybutach), jednakże Piotr powiedział, żeby wykasować komentarze i wprowadzić kod docelowy. Początkowo też chciałem na Kanbanie wprowadzić nowe zadania poprawiające encje o uwagi. Odnośnie jeszcze tego `userId` w `UserEntity`, Adrian już wprowadził zadanie i wykonał poprawkę.

2020-12-10 17:14 UTC, LukaszLizewski commented
Konflikty zostały naprawione

2020-12-11 08:33 UTC, merged