task-JDP201101-22
piotr-grosicki/project-jdp-2011-01 pull request #29
Opened 2020-12-09 21:04 UTC by PaulinaSlowik

Adding the actual implementation of methods in the GroupController.
Creation of a service, mapper and modification of the repository.

2020-12-10 22:27 UTC, ArdianM90 requested changes
W komentarzach zostawiłem uwagi - na pewno trzeba dodać listę produktów do Dto. Nie jestem pewien czy metoda save bez nadpisywania crudRepository zadziała - sprawdzałaś postmanem czy działa?

Przy okazji można mały refactoring zrobić: nie było by lepiej podawać w parametrze "groupService.findAll()" zamiast groupService.findAllProductGroups()? Trzeba też ustalić na czacie czy robimy jeden service, czy każdej encji osobny.

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public void updateGroup(@RequestParam Long groupId) {
W parametrze powinny być przekazane nowe dane do update'u, jeżeli to ma być metoda "updateGroup".

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteProductGroup(groupId);
Chyba że ma być "deleteGroup"...
ale tak naprawdę powninny być obie.

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        return new GroupDto(
GroupDto powinien przechowywać wszystkie dane z jednego rekordu group: id, name i listę produktów.

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        return new GroupEntity(
Brakuje listy produktów. Jeżeli będziemy mapować grupę, do której należą jakieś produkty, to te dane znikną.

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
Tylko tyle? Brakuje np. findByID, save, deleteById.

2020-12-10 22:27 UTC, ArdianM90 commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(groupEntity);
Będzie tak działało, bez nadpisywania oryginalnej metody CrudRepository?

2020-12-11 13:37 UTC, adamrozycki00 requested changes

2020-12-11 13:37 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +    public GroupEntity mapToGroup(final GroupDto groupDto) {
Klasa GroupDto, zgodnie z uwagami mentora w innym PR, powinna mieć listę ProductDto (skoro GroupEntity ma pole products), ewentualnie listę ich id. I dodanie tego pola będzie mieć oczywiście wpływ na mapper.

2020-12-11 13:37 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
@ArdianM90 Nie brakuje chyba. Wymienione metody są w repozytorium. Dlaczego uważasz, że trzeba je przedefiniować?

2020-12-11 13:44 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(groupEntity);
tak, z crud repository nie trzeba nic nadpisywac.

2020-12-11 13:45 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
zgadzam sie, ten interfejs powinien byc pusty chyba ze chcemy dodac jakies nowe metody do tych ktore sa dostarczane przez Crud i Jpa repository

2020-12-11 18:03 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteProductGroup(groupId);
dodatkowo metoda `update` raczej nie powinna usuwac ;)

2020-12-11 23:14 UTC, PaulinaSlowik commented
> W komentarzach zostawiłem uwagi - na pewno trzeba dodać listę produktów do Dto. Nie jestem pewien czy metoda save bez nadpisywania crudRepository zadziała - sprawdzałaś postmanem czy działa?
> 
> Przy okazji można mały refactoring zrobić: nie było by lepiej podawać w parametrze "groupService.findAll()" zamiast groupService.findAllProductGroups()? Trzeba też ustalić na czacie czy robimy jeden service, czy każdej encji osobny.

1.Dodałam listę produktów do Dto. 
2.Sprawdziłam Postmanem klasę GroupCController i jedyne co to dla metody getGroup mam wynik null- zastanawiam się czemu..? (w załączniku printscreen).
3.Zrobiłam refactor zgodnie z powyższym.
![2020-12-12 (1)](https://user-images.githubusercontent.com/67586415/101963411-edb1e700-3c0e-11eb-86a0-116a62361768.png)

2020-12-11 23:15 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +    public void updateGroup(@RequestParam Long groupId) {
Zrobione:

```
    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
    public void updateGroup(@RequestBody GroupDto groupDto) {
        groupService.saveProductGroup(groupMapper.mapToGroup(groupDto));
```

2020-12-11 23:15 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteProductGroup(groupId);
Ostatecznie nie dodałam metody delete.

2020-12-11 23:16 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        return new GroupDto(
Zmieniłam i teraz przechowuje:
```
public class GroupDto {
    private Long id;
    private String groupName;
    private List<ProductDto> productDtoList;
```

2020-12-11 23:17 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +        return new GroupEntity(
Dodałam listę produktów:

```
    public GroupEntity mapToGroup(final GroupDto groupDto) {
        return new GroupEntity(
                groupDto.getId(),
                groupDto.getGroupName(),
                groupDto.getProductDtoList()
        );
```

2020-12-11 23:20 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
Tutaj mam pytanie, ponieważ jak usuwam z GroupRepository :
```
    @Override
    List<GroupEntity> findAll();
```
to niestety wyskakuje mi błąd w GroupService, dlaczego?
Poniżej prt screeny.
![2020-12-12](https://user-images.githubusercontent.com/67586415/101963774-d8898800-3c0f-11eb-975c-c084aa36045c.png)
![2020-12-11 (2)](https://user-images.githubusercontent.com/67586415/101963777-d9bab500-3c0f-11eb-9287-b64823cebbf0.png)

2020-12-11 23:21 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/service/GroupService.java
> +        return groupRepository.save(groupEntity);
metoda save działa.

2020-12-11 23:21 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteProductGroup(groupId);
Zrobione:
```
    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
    public void updateGroup(@RequestBody GroupDto groupDto) {
        groupService.saveProductGroup(groupMapper.mapToGroup(groupDto));
```

2020-12-11 23:23 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +    public GroupEntity mapToGroup(final GroupDto groupDto) {
Dodałam listę produktów:

```
    public GroupEntity mapToGroup(final GroupDto groupDto) {
        return new GroupEntity(
                groupDto.getId(),
                groupDto.getGroupName(),
                groupDto.getProductDtoList()
        );
```

2020-12-11 23:24 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/controller/GroupController.java
> +        groupService.deleteProductGroup(groupId);
Zieniłam:

```
    @RequestMapping(method = RequestMethod.PUT, value = "updateGroup")
    public void updateGroup(@RequestBody GroupDto groupDto) {
        groupService.saveProductGroup(groupMapper.mapToGroup(groupDto));
```

2020-12-12 07:04 UTC, adamrozycki00 approved these changes

2020-12-12 07:04 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<ProductDto> productDtoList;
Zmieniłbym nazwę tego pola na `productDtos`, skoro w GroupEntity jest pole `products` (albo można zmienić to `products` na `productList`). Chociaż i tak nazwy pól w całym projekcie wymagają uzgodnienia, bo nie są konsekwentne.

2020-12-12 07:25 UTC, adamrozycki00 commented
> > W komentarzach zostawiłem uwagi - na pewno trzeba dodać listę produktów do Dto. Nie jestem pewien czy metoda save bez nadpisywania crudRepository zadziała - sprawdzałaś postmanem czy działa?
> > Przy okazji można mały refactoring zrobić: nie było by lepiej podawać w parametrze "groupService.findAll()" zamiast groupService.findAllProductGroups()? Trzeba też ustalić na czacie czy robimy jeden service, czy każdej encji osobny.
> 
> 1.Dodałam listę produktów do Dto.
> 2.Sprawdziłam Postmanem klasę GroupCController i jedyne co to dla metody getGroup mam wynik null- zastanawiam się czemu..? (w załączniku printscreen).
> 3.Zrobiłam refactor zgodnie z powyższym.
> ![2020-12-12 (1)](https://user-images.githubusercontent.com/67586415/101963411-edb1e700-3c0e-11eb-86a0-116a62361768.png)

To jest grubsza sprawa 🙂 Masz puste konstruktory w obu klasach. Najlepiej dodać lombokową adnotację @AllArgsConstructor. Ale wtedy trzeba uzgodnić ostatnie pole, które powinno mapować na ProductDto (albo vice versa). Ale nie ma jeszcze ProductMappera gotowego w projekcie 🙂 Ja tymczasem poradziłem sobie, dając nowe (puste) ArrayLists w tych ostanich polach w grupowych mapperach. Wtedy GET działa poprawnie, w ostatnim polu zwracając pustą listę.

2020-12-12 07:36 UTC, adamrozycki00 requested changes

2020-12-12 07:36 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/GroupEntity.java
> +    public GroupEntity(Long id, String groupName, List<ProductDto> productDtoList) {
Pusty konstruktor, nie inicjuje pól, zamieniłbym go na adnotację @AllArgsConstructor.

2020-12-12 07:36 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                groupDto.getProductDtoList()
Tu powinna być chyba lista produktów zamiast DTO produktów, ale nie ma jeszcze gotowego ProductMappera.

2020-12-12 07:36 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                groupEntity.getProducts()
Tu z kolei powinna być chyba lista DTO zamiast produktów, ale nie ma jeszcze gotowego ProductMappera.

2020-12-12 07:36 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    public GroupDto(Long id, String name, List<ProductEntity> products) {
Pusty konstruktor, nie inicjuje pól, zamieniłbym go na adnotację @AllArgsConstructor.

2020-12-12 07:41 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
Oryginalna metoda z interfejsu zwraca Iterable, a opakowująca ją metoda w serwisie zwraca List.

2020-12-12 13:01 UTC, adamrozycki00 commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
Ale jeśli zmienisz interfejs na `JpaRepository` (zamiast `CrudRepository`), to tam oryginalna metoda zwraca już `List`, i nie trzeba jej przedefiniowywać. Więc najlepiej tak zrobić, zresztą uzgadnialiśmy na poprzednim spotkaniu, że robimy wszędzie `JpaRepository`.

2020-12-12 14:31 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java
> +    List<GroupEntity> findAll();
Zmieniłam interfejs na JpaRepository

2020-12-12 14:32 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    private List<ProductDto> productDtoList;
Zmieniona nazwa na productDtos

2020-12-12 14:33 UTC, PaulinaSlowik commented
> > > W komentarzach zostawiłem uwagi - na pewno trzeba dodać listę produktów do Dto. Nie jestem pewien czy metoda save bez nadpisywania crudRepository zadziała - sprawdzałaś postmanem czy działa?
> > > Przy okazji można mały refactoring zrobić: nie było by lepiej podawać w parametrze "groupService.findAll()" zamiast groupService.findAllProductGroups()? Trzeba też ustalić na czacie czy robimy jeden service, czy każdej encji osobny.
> > 
> > 
> > 1.Dodałam listę produktów do Dto.
> > 2.Sprawdziłam Postmanem klasę GroupCController i jedyne co to dla metody getGroup mam wynik null- zastanawiam się czemu..? (w załączniku printscreen).
> > 3.Zrobiłam refactor zgodnie z powyższym.
> > ![2020-12-12 (1)](https://user-images.githubusercontent.com/67586415/101963411-edb1e700-3c0e-11eb-86a0-116a62361768.png)
> 
> To jest grubsza sprawa 🙂 Masz puste konstruktory w obu klasach. Najlepiej dodać lombokową adnotację @AllArgsConstructor. I trzeba jeszcze uzgodnić ostatni argument konstruktora wywoływanego w obu metodach mappera, który powinien być zmapowany na ProductDto (albo vice versa). Ale nie ma jeszcze ProductMappera gotowego w projekcie 🙂 Ja tymczasem poradziłem sobie w testach, dając nowe (puste) ArrayLists jako ostatni parametr konstruktora wywoływanego w obu metodach grupowego mappera. Wtedy GET działa poprawnie, w ostatnim polu zwracając pustą listę.

wpisałąm ArrayListy w maperze ponieważ nie ma jeszcze ProductMappera

2020-12-12 14:34 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
> +    public GroupDto(Long id, String name, List<ProductEntity> products) {
dodałam adnotację @AllArgsConstructor i usunełam pusty kontruktor

2020-12-12 14:34 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/GroupEntity.java
> +    public GroupEntity(Long id, String groupName, List<ProductDto> productDtoList) {
dodałam adnotację @AllArgsConstructor i usunełam pusty kontruktor

2020-12-12 14:35 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                groupEntity.getProducts()
wpisałąm ArrayListy w maperze ponieważ nie ma jeszcze ProductMappera

2020-12-12 14:35 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
> +                groupDto.getProductDtoList()
wpisałąm ArrayListy w maperze ponieważ nie ma jeszcze ProductMappera

2020-12-12 14:44 UTC, adamrozycki00 reviewed
Czekamy na `ProductMapper`.
@ArdianM90 Adrian, ten product mapper powinien mieć metody mapujące listy w obie strony: listę produktów na listę DTO i vice versa.

2020-12-12 18:38 UTC, ArdianM90 commented
Dodana metoda mapująca w drugą stronę. Mapowaniem funkcją, która rzuca błąd, więc może być ciężkie w odbiorze, ale zrobiłem też test sprawdzający czy to działa. I wygląda na to, że działa.

2020-12-14 19:24 UTC, LukaszLizewski approved these changes
Jak dla mnie OK.

2020-12-14 19:24 UTC, LukaszLizewski commented on src/main/java/com/kodilla/ecommercee/domain/GroupEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
`GenerationType.IDENTITY`, osobiście zostawiłbym `AUTO` ale jak działa to można zostawić.

2020-12-14 20:57 UTC, adamrozycki00 approved these changes

2020-12-14 22:33 UTC, PaulinaSlowik commented on src/main/java/com/kodilla/ecommercee/domain/GroupEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
działa

2020-12-14 22:53 UTC, piotr-grosicki approved these changes

2020-12-14 22:53 UTC, merged