task-JDP2011010-17
piotr-grosicki/project-jdp-2011-01 pull request #30
Opened 2020-12-12 20:59 UTC by aleksander-lockhart

Zmiana ProductRepository na CrudRepository<ProductEntity, Long> (w product Entity Id jest Long, w Repository było CrudRepository<ProductEntity, Int>). Testy obejmują Create, Read, Update i delete (choć według rozmowy z piątku jest to niepotrzebne, ale dodane na potrzeby nauki i zmian repository)

2020-12-12 22:37 UTC, adamrozycki00 reviewed
Brakuje drobnej rzeczy - testu relacji (co się usuwa, a co zostaje w bazie, gdy usuniemy produkt).
I dziwna rzecz: PR z testami tej samej encji (#26 )  wrzucił wcześniej Adrian @ArdianM90 . W którym akurat są testy relacji. Więc może połączyć kod z obu PR-ów?

2020-12-13 09:07 UTC, aleksander-lockhart commented
> Brakuje drobnej rzeczy - testu relacji (co się usuwa, a co zostaje w bazie, gdy usuniemy produkt).
> I dziwna rzecz: PR z testami tej samej encji (#26 ) wrzucił wcześniej Adrian @ArdianM90 . W którym akurat są testy relacji. Więc może połączyć kod z obu PR-ów?

Jeżeli chodzi o delete - to został dodany bardziej "pro forma". Po rozmowie na spotkaniu docelowo usunąłem całkowicie testowanie tej funkcji (zgodnie z z tym, że ze sklepu nie kasuje się produktów - aby nie mieć rozjechanej bazy i braków w starych zamówieniach).

Co do #26 - część testów się powtarza, bądź jest prawie taka sama. W końcu testujemy encje, które są ze sobą powiązane - więc można je testować "z drugiej strony", a test będzie wyglądał prawie tak samo.

2020-12-13 09:16 UTC, adamrozycki00 approved these changes

2020-12-13 09:22 UTC, ArdianM90 commented
No dobra, ale delete jest, bo się przydaje w chociażby w testach. Może warto było by testować czy usunięcie produktu nie usuwa razem z nim grupy (mogą do niej należeć inne produkty).

2020-12-13 09:31 UTC, adamrozycki00 commented
Nie jest konieczne oprogramowanie metody `DELETE`, bo metody usuwające `deleteAll` i `deleteById`, które mogą być potrzebne w testach, są i tak w repozytorium.

2020-12-13 12:11 UTC, aleksander-lockhart commented
> No dobra, ale delete jest, bo się przydaje w chociażby w testach. Może warto było by testować czy usunięcie produktu nie usuwa razem z nim grupy (mogą do niej należeć inne produkty).

Zgadzam się, dodany test sprawdzający ilość grup przed i po usunięciu produktu.

2020-12-13 12:40 UTC, adamrozycki00 approved these changes

2020-12-14 08:23 UTC, piotr-grosicki requested changes
konflikt

2020-12-14 10:21 UTC, aleksander-lockhart commented
> konflikt

Rozwiązany. Do tego wyszedł dodatkowy błąd w testach Cart - zła nazwa metody: getProductName został zamieniony na getName.

2020-12-14 10:29 UTC, DagmaraSkorupska approved these changes

2020-12-14 10:50 UTC, piotr-grosicki approved these changes

2020-12-14 10:50 UTC, merged