Utworzona encja product - bez relacji
piotr-grosicki/project-jdp-2011-01 pull request #6
Opened 2020-11-22 10:47 UTC by ArdianM90

2020-11-22 15:17 UTC, piotr-grosicki requested changes
w tym zadaniu relacja `product` juz powinna miec relacje. jezeli zadna z encji jeszcze nie zostala przez kogos utworzona nalezy stworzyc wydmuszke, ktora bedzie tylko sluzyla do zaimplementowania relacji

2020-11-26 07:42 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2020-11-26 07:42 UTC, piotr-grosicki commented on build.gradle
> +    compile('org.springframework.boot:spring-boot-starter-data-jpa')
dlaczego ta zmiana? implementation robi dokladnie to samo co compile :)

2020-11-26 07:42 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/Cart.java
> +    @NotNull
w hibernate not null ustawia sie na kolumnie (https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/Column.html#nullable())

2020-11-26 07:42 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +spring.datasource.url=jdbc:mysql://localhost:3306/kodilla_course?serverTimezone=Europe/Warsaw&useSSL=False
zmian w tym pliku nie powinno tutaj byc. testy musza uruchamiac sie na bazie h2, nie mysql

2020-11-27 08:05 UTC, piotr-grosicki requested changes

2020-11-27 08:05 UTC, piotr-grosicki commented on src/main/resources/application.properties
> +spring.datasource.driver-class-name=org.h2.Driver
na odwrot zmiany: w tym pliku powinien byc mysql

2020-11-27 08:05 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +spring.datasource.username=kodilla_user
a w tym baza h2

2020-11-27 16:08 UTC, piotr-grosicki requested changes

2020-11-27 16:08 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +domain.datasource.driver-class=com.mysql.jdbc.Driver;
wciaz jest zle, w testach uzywamy h2, w normalnie odpalanej aplikacji uzywamy mysql

2020-11-27 16:08 UTC, piotr-grosicki commented on src/test/resources/application.properties
> +domain.datasource.driver-class=com.mysql.jdbc.Driver;
jak dla mnie to jakiekolwiek zmiany w tym pliku sa bledne

2020-11-28 18:15 UTC, LukaszLizewski approved these changes
For me OK.

2020-11-29 11:13 UTC, piotr-grosicki approved these changes

2020-11-29 11:13 UTC, merged